### ISSUE TITLE
Avro Dependecy issue 

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-PushEndpoint#31]
Due to the recent dependency updates, getting the following error on all POST requests

```
[2021-06-25 12:38:50,754] ERROR - [500] POST garmin/dailies (UnhandledExceptionMapper.kt:30)
java.lang.NoSuchMethodError: 'java.lang.String org.apache.avro.Schema.toString(java.util.Collection, boolean)'
	at io.confluent.kafka.schemaregistry.avro.AvroSchema.canonicalString(AvroSchema.java:151) ~[deprecated-javax-0.2.0-all.jar:?]
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:213) ~[deprecated-javax-0.2.0-all.jar:?]
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:275) ~[deprecated-javax-0.2.0-all.jar:?]
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:251) ~[deprecated-javax-0.2.0-all.jar:?]
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:103) ~[deprecated-javax-0.2.0-all.jar:?]
	at io.confluent.kafka.serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:61) ~[deprecated-javax-0.2.0-all.jar:?]
	at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62) ~[deprecated-javax-0.2.0-all.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:917) ~[deprecated-javax-0.2.0-all.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:885) ~[deprecated-javax-0.2.0-all.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:773) ~[deprecated-javax-0.2.0-all.jar:?]
	at org.radarbase.gateway.kafka.KafkaAvroProducer.produce(KafkaAvroProducer.kt:37) ~[radar-push-endpoint-0.2.0.jar:?]
	at org.radarbase.gateway.kafka.ProducerPool.produce(ProducerPool.kt:48) ~[radar-push-endpoint-0.2.0.jar:?]
	at org.radarbase.push.integration.garmin.service.GarminHealthApiService.processDailies(GarminHealthApiService.kt:84) ~[radar-push-endpoint-0.2.0.jar:?]
	at org.radarbase.push.integration.garmin.resource.GarminPushEndpoint$addDalies$1.invoke(GarminPushEndpoint.kt:34) ~[radar-push-endpoint-0.2.0.jar:?]
	at org.radarbase.push.integration.garmin.resource.GarminPushEndpoint$addDalies$1.invoke(GarminPushEndpoint.kt:33) ~[radar-push-endpoint-0.2.0.jar:?]
	at org.radarbase.push.integration.garmin.resource.GarminPushEndpoint.processResponses(GarminPushEndpoint.kt:132) ~[radar-push-endpoint-0.2.0.jar:?]
	at org.radarbase.push.integration.garmin.resource.GarminPushEndpoint.addDalies(GarminPushEndpoint.kt:33) ~[radar-push-endpoint-0.2.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-3.0.2.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[jersey-server-3.0.2.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[jersey-server-3.0.2.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[jersey-server-3.0.2.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-3.0.2.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475) ~[jersey-server-3.0.2.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397) ~[jersey-server-3.0.2.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[jersey-server-3.0.2.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255) [jersey-server-3.0.2.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [jersey-common-3.0.2.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [jersey-common-3.0.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [jersey-common-3.0.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [jersey-common-3.0.2.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [jersey-common-3.0.2.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [jersey-common-3.0.2.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234) [jersey-server-3.0.2.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) [jersey-server-3.0.2.jar:?]
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:356) [jersey-container-grizzly2-http-3.0.2.jar:?]
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190) [grizzly-http-server-3.0.0.jar:3.0.0]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) [grizzly-framework-3.0.0.jar:3.0.0]
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) [grizzly-framework-3.0.0.jar:3.0.0]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

Seems like the avro version used in [RADAR-Schemas](https://github.com/RADAR-base/RADAR-Schemas/blob/20acf3ab40171f13ddaf9d724813d393f5d3aade/java-sdk/build.gradle#L26) i.e. [avro 1.9.2](https://avro.apache.org/docs/1.9.2/api/java/org/apache/avro/Schema.html) does not support that method while the latest confluent uses a newer version which does. 

So the solution is to either -

1. Update the avro version in RADAR-Schemas, create a new release and use it here, or
2. Downgrade the confluent version here for now until schema repo has been updated

**Comment by blootsvoets** [comment]
Updating AVRO is fine. I’ve kept avro pinned to 1.9.2 because otherwise Android cannot be supported, but for server JVM’s the latest avro is fine.
